pipeline {

    agent any

    stages {

        stage('Generate Version') {
            steps {
                script {
                    env.APP_VERSION = "1.0.${BUILD_NUMBER}"
                    echo "Application Version: ${env.APP_VERSION}"
                }
            }
        }

        stage('CI Pipeline') {
            steps {

                echo "Starting CI Pipeline..."
                echo "Version: ${APP_VERSION}"

                build(
                    job: 'crm-dev-CI',
                    parameters: [
                        string(
                            name: 'APP_VERSION',
                            value: "${APP_VERSION}"
                        )
                    ],
                    wait: true
                )
            }
        }

        stage('CD Pipeline') {
            steps {

                echo "CI Pipeline completed successfully."
                echo "Starting CD Pipeline..."
                echo "Deploying version: ${APP_VERSION}"

                build(
                    job: 'crm-dev-CD',
                    parameters: [
                        string(
                            name: 'APP_VERSION',
                            value: "${APP_VERSION}"
                        )
                    ],
                    wait: true
                )
            }
        }
    }

    post {

        success {
            echo """
======================================
CRM-DEV CI/CD SUCCESS
======================================

Application : crm-dev
Version     : ${APP_VERSION}

CI completed successfully.
CD completed successfully.

======================================
"""
        }

        failure {
            echo """
======================================
CRM-DEV CI/CD FAILED
======================================

Application : crm-dev
Version     : ${APP_VERSION}

Check Jenkins console logs.

======================================
"""
        }
    }
}