pipeline {
    agent any

    parameters {
        string(
            name: 'APP_VERSION',
            defaultValue: '',
            description: 'Leave empty for automatic version 1.0.BUILD_NUMBER, or enter an existing version such as 1.0.3'
        )
    }

    stages {

        stage('Generate Version') {
            steps {
                script {
                    if (params.APP_VERSION?.trim()) {
                        env.APP_VERSION = params.APP_VERSION.trim()
                    } else {
                        env.APP_VERSION = "1.0.${env.BUILD_NUMBER}"
                    }

                    echo "Application Version: ${env.APP_VERSION}"
                }
            }
        }

        stage('Run CI') {
            steps {
                build job: 'crm-dev-CI',
                    parameters: [
                        string(
                            name: 'APP_VERSION',
                            value: env.APP_VERSION
                        )
                    ],
                    wait: true,
                    propagate: true
            }
        }

        stage('Run CD') {
            steps {
                build job: 'crm-dev-CD',
                    parameters: [
                        string(
                            name: 'APP_VERSION',
                            value: env.APP_VERSION
                        )
                    ],
                    wait: true,
                    propagate: true
            }
        }
    }

    post {
        success {
            echo "CI/CD completed successfully."
            echo "Deployed Version: ${env.APP_VERSION}"
        }

        failure {
            echo "CI/CD pipeline failed."
            echo "Check the failed CI or CD job."
        }
    }
}